### ISSUE TITLE
No such file or directory `/opt/boxen/homebrew/bin/git-credential-osxkeychain`

### ISSUE THREAD

**Issue by sebroeder** [boxen/puppet-git#64]
I use boxen with homebrew installed to `/usr/local` with the following config in `facts.d/homebrew_root.yaml`:

```yaml
---
homebrew_root: /usr/local
```

When I run a `git push` I get the following Ruby exception:

```
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:37:in `exec': No such file or directory - /opt/boxen/homebrew/bin/git-credential-osxkeychain (Errno::ENOENT)
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:37:in `block in popen4'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:85:in `call'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:85:in `block in do_popen'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:62:in `fork'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:62:in `do_popen'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/open4-1.3.4/lib/open4.rb:34:in `popen4'
	from /opt/boxen/bin/boxen-git-credential:45:in `<main>'
```

On my system `git-credential-osxkeychain` is installed to:

```bash
$ which git-credential-osxkeychain
/usr/local/bin/git-credential-osxkeychain
```

I think the offender are lines 42/43 in `/opt/boxen/bin/boxen-git-credential`:

```ruby
  fallback   = ENV["BOXEN_GIT_CREDENTIAL_FALLBACK"]
  fallback ||= "#{config.homedir}/homebrew/bin/git-credential-osxkeychain"
```

I cannot even get it to work when I `export BOXEN_GIT_CREDENTIAL_FALLBACK=/usr/local/bin/git-credential-osxkeychain` before I run `git push`.

**Comment by sebroeder** [comment]
I am closing this as a duplicate for boxen/our-boxen#727.
